# Generated by Django 5.2.9 on 2026-01-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhook", "0006_whatsappoutgoingmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="whatsappcall",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "WhatsApp Call",
                "verbose_name_plural": "WhatsApp Calls",
            },
        ),
        migrations.AlterModelOptions(
            name="whatsappmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "WhatsApp Message",
                "verbose_name_plural": "WhatsApp Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="whatsappmessagestatus",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "WhatsApp Message Status",
                "verbose_name_plural": "WhatsApp Message Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="whatsappoutgoingmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "WhatsApp Outgoing Message",
                "verbose_name_plural": "WhatsApp Outgoing Messages",
            },
        ),
    ]
