# Generated by Django 5.2.9 on 2026-01-12 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0003_flow_webhook_secret_flow_webhook_verified_and_more"),
        ("webhook", "0007_alter_whatsappcall_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="flow",
            field=models.ForeignKey(
                blank=True,
                help_text="The flow that received this message via webhook",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_messages",
                to="flows.flow",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["flow", "-created_at"], name="webhook_wha_flow_id_20ecdf_idx"
            ),
        ),
    ]
