# Generated by Django 6.0 on 2025-12-29 06:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("flow_json", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("version", models.IntegerField(default=1)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("chat", "Chat"),
                            ("call", "Voice Call"),
                            ("webhook", "Webhook"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                (
                    "webhook_path",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_flows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "flows",
                "ordering": ["-updated_at"],
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_user_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("state", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="flows.flow",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flow_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                            ("tool", "Tool"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("tool_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "tool_call_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="flows.session",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("input_message", models.TextField()),
                ("output_message", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_traceback", models.TextField(blank=True, default="")),
                ("tokens_input", models.IntegerField(default=0)),
                ("tokens_output", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="flows.flow",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="flows.session",
                    ),
                ),
            ],
            options={
                "db_table": "flow_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("secret", models.CharField(max_length=64)),
                ("allowed_methods", models.JSONField(default=list)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("api_key", "API Key"),
                            ("bearer", "Bearer Token"),
                            ("basic", "Basic Auth"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("rate_limit", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="flows.flow",
                    ),
                ),
            ],
            options={
                "db_table": "webhooks",
            },
        ),
        migrations.CreateModel(
            name="FlowVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField()),
                ("flow_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="flows.flow",
                    ),
                ),
            ],
            options={
                "db_table": "flow_versions",
                "ordering": ["-version"],
                "unique_together": {("flow", "version")},
            },
        ),
    ]
