# Generated by Django 5.2.9 on 2026-01-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0002_add_react_flow_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="webhook_secret",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique secret token for webhook URL (used for routing)",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="webhook_verified",
            field=models.BooleanField(
                default=False, help_text="Whether webhook is verified with Meta"
            ),
        ),
        migrations.DeleteModel(
            name="Webhook",
        ),
    ]
